language: cpp
matrix:
  include:
    # Windows MSVC x64
    - os: windows
      name: win64
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DFG_EXTERNALS_USE_PREBUILD=ON .. 
        - cmake --build . --config Release
      
